### ISSUE TITLE
Add README. explaining the project, attaching the required screen shots. 

### ISSUE THREAD

**Issue by SohamDave08** [SohamDave08/AllAboutCovid19#10]
![Screenshot (165)](https://user-images.githubusercontent.com/51802431/94809988-1187ce00-0411-11eb-994b-37654bcbd37c.png)
![Screenshot (166)](https://user-images.githubusercontent.com/51802431/94809991-12b8fb00-0411-11eb-8b64-830d25d823f1.png)
![Screenshot (167)](https://user-images.githubusercontent.com/51802431/94809995-13519180-0411-11eb-9714-05892ed770f4.png)

**Comment by RajvirSingh1313** [comment]
Hi can i help??

**Comment by RajvirSingh1313** [comment]
Hi ??
