### ISSUE TITLE
Replacing the Public API for Global cases in COVID-19 tracker app

### ISSUE THREAD

**Issue by SohamDave08** [SohamDave08/AllAboutCovid19#5]
Currently (https://covid19-server.chrismichael.now.sh/api/v1/AllReports) is used for global cases.

Since the API aren't available for deployment, try replacing the project structure with the following API:
Global cases (Home.vue) - https://api.covid19api.com/summary

**Comment by bmusuko** [comment]
Hello, can i try this issue?

**Comment by SohamDave08** [comment]
Yes @bmusuko. Please give it a try. All the best
